#
# kind create cluster --config kind-config.yaml
#
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /c/data
        containerPath: /data
